language: php
php:
- 5.5
- 5.6
install: composer install
notifications:
  slack:
    secure: zwBe5X4WltLEEijHaOXU3xgQVcLT7tlqcNsT9+anekpdV6NlloZm2oZ9L1F8fBUliCSPZ5berYZvd8U38TOB1h6dGtg+rHZZhra4lHGBaX3RtVG2abJqIrWxnleGLEDnutqFn/dyMLM/+Uj/ivQbgD0dMLLTjuTphRtRDhVV3/pPQscA/2cBRp+UoOGBJt2WBUnZ1Z6TrOaxEIy+ojYCgm/MTDGD2ZbYQXI1ak4KW6cuTTPoAFaKYTBI7CH6jopNuuaFOFfWjAPr3EQeiAZzHdcPow6OPANItczeZmF5MoEVSvztbfMw1XsSAKOVtkEX5tU71jhSUxrod3+MLahLH3YZYrSvbDco0gVxphHQvpM9aJfuQLMBcjI2vfXa2WkUuvxZStLL4zzlz3ENWa77gHq/F/w9hrX1gn3QDvjwhGFa9URunbUs2eg7qUUTmaEjcnvGseFZX2a/iDDuo0tkLZ9MudloyFll7kciNyTQoGyH+uQKrQ84ro435JyEW9AhsoBLeDKt2vakH7cVVieRh+M8ihzVWU9LW6LpR9ayvW2NyK1ttA6+kNzv0d9HGXZeeBE5z5sjTeIqRw6A7xe88yWZr2SNfW5X05OyrJX98buXg8WX9N61nvLkQrmbI49GiUnPbsOt8EnuUMPXZzeaoQZjAkRbqNyeDzABBrq5Nm4=
